services:
  distdepth:
    build: .
    tty: true
    working_dir: /app
    entrypoint: ['bash']
    volumes:
      - ./:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]